name: publish Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
      IOS_KEY: ${{ secrets.IOS_KEY }}
      ANDROID_KEY: ${{ secrets.ANDROID_KEY }}
      IOS_VERSION: ${{ vars.IOS_VERSION }}
      IOS_BUILD_NUMBER: ${{ vars.IOS_BUILD_NUMBER }}
      IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
      ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
      ANDROID_VERSION: ${{ vars.ANDROID_VERSION }}
      ANDROID_BUILD_NUMBER: ${{ vars.ANDROID_BUILD_NUMBER }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  release-tag:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get package version
        id: version
        run: echo ::set-output name=tag::$(jq -r '.version' package.json)

      - name: Create Git Tag
        run: git tag ${{ steps.version.outputs.tag }} && git push origin ${{ steps.version.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.tag }}
          body: Release ${{ steps.version.outputs.tag }}

  build-and-publish-npm-github:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jimmyvos'

      - name: replace package name
        uses: maxgfr/github-change-json@v0.0.21
        with:
          path: 'package.json'
          key: 'name'
          value: '@jimmyvos/release-to-app-store'

      - run: npm ci
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
